backend:
  name: git-gateway
  branch: cmstest

media_folder: "static/images/uploads"  
collections:
  - name: "config"
    label: "Molecules"
    files:
      - name: "navbar"
        label: "Navbar Configuration"
        file: "src/cms_molecules/Navbar/config.md"
        fields:
          - {label: "Button Color", name: "buttonConfig.color", widget: "string"}
          - {label: "Button Size", name: "buttonConfig.size", widget: "string"}
          - {label: "Button Edge", name: "buttonConfig.edge", widget: "string"}
        preview_path: "public/cms/preview-templates/NavbarPreview.tsx"